version: "0.1.7"
app:
  container_name: vs-frontend-frontend-container
  build:
    context: .
    dockerfile: ./apps/frontend/Dockerfile
  restart: always
  environment:
    - VITE_APP_ENV=production
  ports:
    - 3000:3000

services:
  backend:
    image: backend
    container_name: vs-backend-container
    build:
    context: .
    dockerfile: ./apps/backend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./apps/backend/.env